name: make_docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      # - run: apt-get install pngquant 
      - run: pip install git+https://${{ secrets.GH_MATERIAL_MKDOCS_TOKEN }}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: pip install mkdocs-jupyter
      - run: pip install pillow cairosvg # install social share card plugins

      # Copy required notebooks to docs folder
      - run: cp section-2-data-science-and-ml-tools/introduction-to-numpy.ipynb docs/
      - run: cp section-2-data-science-and-ml-tools/introduction-to-pandas.ipynb docs/
      - run: cp section-2-data-science-and-ml-tools/introduction-to-matplotlib.ipynb docs/
      - run: cp section-2-data-science-and-ml-tools/introduction-to-scikit-learn.ipynb docs/
      - run: cp communicating-your-work.md docs/
      - run: cp section-4-unstructured-data-projects/end-to-end-dog-vision-v2.ipynb docs/
      - run: cp images/* docs/images/

      # Last step to deploy docs
      - run: mkdocs gh-deploy --force
